"""
@file test_listing.py

@brief Tests for assembler listing generation.
"""

import unittest

from assembler.codegen import CodeGenerationRecord
from assembler.listing import ListingGenerator


class ListingGeneratorTest(unittest.TestCase):
    """
    @brief Tests for ListingGenerator.
    """

    def setUp(self) -> None:
        self._generator = ListingGenerator()

    def test_listing_contains_line_address_opcode_and_source(self) -> None:
        """
        @brief Verify the basic listing format.
        """
        source = (
            "ORG 0x200\n"
            "Start: CLS\n"
            "JP Start\n"
        )
        records = (
            CodeGenerationRecord( line=2, address=0x0200, data=b"\x00\xE0"),
            CodeGenerationRecord( line=3, address=0x0202, data=b"\x12\x00"),
        )
        listing = self._generator.generate(source, records)
        self.assertEqual(
            listing,
            "   1                  ORG 0x200\n"
            "   2  0200  00 E0     Start: CLS\n"
            "   3  0202  12 00     JP Start"
        )


    def test_listing_preserves_long_labels(self) -> None:
        """
        @brief Verify that long labels are preserved in the source column.
        """
        source = ( "VeryLongLabelNameThatMustNotBeTruncated: CLS\n")
        records = ( CodeGenerationRecord( line=1, address=0x0200, data=b"\x00\xE0"),)
        listing = self._generator.generate(source, records)
        self.assertIn( "VeryLongLabelNameThatMustNotBeTruncated: CLS", listing)


    def test_listing_preserves_unemitted_source_lines(self) -> None:
        """
        @brief Verify that source lines without generated bytes remain in
        the listing.
        """
        source = (
            "; comment\n"
            "ORG 0x200\n"
            "CLS\n"
        )
        records = ( CodeGenerationRecord( line=3, address=0x0200, data=b"\x00\xE0"),)
        listing = self._generator.generate(source, records)
        lines = listing.splitlines()
        self.assertEqual(len(lines), 3)
        self.assertIn("; comment", lines[0])
        self.assertIn("ORG 0x200", lines[1])
        self.assertIn("CLS", lines[2])


